version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  buildAndDeploy:
    docker:
      - image: "cimg/node:16.15.0"
    steps:
      - node/install:
          node-version: '16.15.0'         
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: npm run frontend:install
      - run:
          name: Install API Dependencies
          command: npm run api:install
      - run:
          name: Front-End Lint
          command: npm run frontend:lint
      - run:
          name: Front-End Build
          command: npm run frontend:build
      - run:
          name: API Build
          command: npm run api:build

      - run:
          name: App Deploy
          command: npm run deploy
            
workflows:
  udagram:
    jobs:
      - buildAndDeploy:
